### PR TITLE
Morphology collage improvements

### PR DESCRIPTION
**Pull request by hernando**
- Bugfix in world to axes matrix calculation.
- Better cell selection algorithm based on optimizing the minimum
  intercellular distance to reach the desired number of cells per
  image.
- Scale fonts, margins and axes depending on the output image size.
- Removed unused option for clipping neurons
- Workarounds for undesired clipping in neurons after scene clean-up
  (potentially caused by on OSG bug).

### CODE REVIEW

**Comment by hernando** [comment]
Fixes #13

**Comment by karjonas** [comment]
This would have been easier to review if it was several commits

**Comment by hernando** [comment]
Yes, but I was in a rush to fix it. I can try splitting it if it really bothers you.

**Comment by karjonas** [comment]
I am not familiar with the code and I think no one else is anyway so I will just approve then.

**Comment by hernando** [comment]
And I'm afraid that whenever you try doing the collage with Brayns you will trash this code and rewrite it from scratch :disappointed:

**Pull request merged**
